<a href="https://colab.research.google.com/github/Veditha08/learning_machinelearning/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
#get dimension
a.ndim

1

In [6]:
b = np.array([[1,2,3],[2,3,5]])
#get shape
b.shape

(2, 3)

In [12]:
#get specific element [r, c]
b[1, 2]

np.int64(5)

In [14]:
#get specific row [1, :]; get specific column [:, 2]
b[0, :]
b[:, 1]

array([2, 3])

In [17]:
lap_times = np.array([1,2,3,4])
#in minutes:
lap_in_secs = lap_times * 60
print(lap_in_secs)

[ 60 120 180 240]
